export const quickPickTitleMaxChars = 80;
export const ImageMimetypes: Record<string, string> = {
	'.png': 'image/png',
	'.gif': 'image/gif',
	'.jpg': 'image/jpeg',
	'.jpeg': 'image/jpeg',
	'.jpe': 'image/jpeg',
	'.webp': 'image/webp',
	'.tif': 'image/tiff',
	'.tiff': 'image/tiff',
	'.bmp': 'image/bmp',
};

export const enum CharCode {
	/**
	 * The `/` character.
	 */
	Slash = 47,
	/**
	 * The `\` character.
	 */
	Backslash = 92,
	A = 65,
	Z = 90,
	a = 97,
	z = 122,
}

export const enum Colors {
	GutterBackgroundColor = 'mintlens.gutterBackgroundColor',
	GutterForegroundColor = 'mintlens.gutterForegroundColor',
	GutterUncommittedForegroundColor = 'mintlens.gutterUncommittedForegroundColor',
	TrailingLineBackgroundColor = 'mintlens.trailingLineBackgroundColor',
	TrailingLineForegroundColor = 'mintlens.trailingLineForegroundColor',
	LineHighlightBackgroundColor = 'mintlens.lineHighlightBackgroundColor',
	LineHighlightOverviewRulerColor = 'mintlens.lineHighlightOverviewRulerColor',
	ClosedAutolinkedIssueIconColor = 'mintlens.closedAutolinkedIssueIconColor',
	ClosedPullRequestIconColor = 'mintlens.closedPullRequestIconColor',
	OpenAutolinkedIssueIconColor = 'mintlens.openAutolinkedIssueIconColor',
	OpenPullRequestIconColor = 'mintlens.openPullRequestIconColor',
	MergedPullRequestIconColor = 'mintlens.mergedPullRequestIconColor',
	UnpublishedChangesIconColor = 'mintlens.unpublishedChangesIconColor',
	UnpublishedCommitIconColor = 'mintlens.unpublishedCommitIconColor',
	UnpulledChangesIconColor = 'mintlens.unpulledChangesIconColor',
}

export const enum Commands {
	ActionPrefix = 'mintlens.action.',

	AddAuthors = 'mintlens.addAuthors',
	BrowseRepoAtRevision = 'mintlens.browseRepoAtRevision',
	BrowseRepoAtRevisionInNewWindow = 'mintlens.browseRepoAtRevisionInNewWindow',
	BrowseRepoBeforeRevision = 'mintlens.browseRepoBeforeRevision',
	BrowseRepoBeforeRevisionInNewWindow = 'mintlens.browseRepoBeforeRevisionInNewWindow',
	ClearFileAnnotations = 'mintlens.clearFileAnnotations',
	CloseUnchangedFiles = 'mintlens.closeUnchangedFiles',
	CloseWelcomeView = 'mintlens.closeWelcomeView',
	CompareWith = 'mintlens.compareWith',
	CompareHeadWith = 'mintlens.compareHeadWith',
	CompareWorkingWith = 'mintlens.compareWorkingWith',
	ComputingFileAnnotations = 'mintlens.computingFileAnnotations',
	ConnectRemoteProvider = 'mintlens.connectRemoteProvider',
	CopyCurrentBranch = 'mintlens.copyCurrentBranch',
	CopyMessageToClipboard = 'mintlens.copyMessageToClipboard',
	CopyRemoteBranchesUrl = 'mintlens.copyRemoteBranchesUrl',
	CopyRemoteBranchUrl = 'mintlens.copyRemoteBranchUrl',
	CopyRemoteCommitUrl = 'mintlens.copyRemoteCommitUrl',
	CopyRemoteComparisonUrl = 'mintlens.copyRemoteComparisonUrl',
	CopyRemoteFileUrl = 'mintlens.copyRemoteFileUrlToClipboard',
	CopyRemoteFileUrlWithoutRange = 'mintlens.copyRemoteFileUrlWithoutRange',
	CopyRemoteFileUrlFrom = 'mintlens.copyRemoteFileUrlFrom',
	CopyRemoteIssueUrl = 'mintlens.copyRemoteIssueUrl',
	CopyRemotePullRequestUrl = 'mintlens.copyRemotePullRequestUrl',
	CopyRemoteRepositoryUrl = 'mintlens.copyRemoteRepositoryUrl',
	CopyShaToClipboard = 'mintlens.copyShaToClipboard',
	CreatePullRequestOnRemote = 'mintlens.createPullRequestOnRemote',
	DiffDirectory = 'mintlens.diffDirectory',
	DiffDirectoryWithHead = 'mintlens.diffDirectoryWithHead',
	DiffWith = 'mintlens.diffWith',
	DiffWithNext = 'mintlens.diffWithNext',
	DiffWithNextInDiffLeft = 'mintlens.diffWithNextInDiffLeft',
	DiffWithNextInDiffRight = 'mintlens.diffWithNextInDiffRight',
	DiffWithPrevious = 'mintlens.diffWithPrevious',
	DiffWithPreviousInDiffLeft = 'mintlens.diffWithPreviousInDiffLeft',
	DiffWithPreviousInDiffRight = 'mintlens.diffWithPreviousInDiffRight',
	DiffLineWithPrevious = 'mintlens.diffLineWithPrevious',
	DiffWithRevision = 'mintlens.diffWithRevision',
	DiffWithRevisionFrom = 'mintlens.diffWithRevisionFrom',
	DiffWithWorking = 'mintlens.diffWithWorking',
	DiffWithWorkingInDiffLeft = 'mintlens.diffWithWorkingInDiffLeft',
	DiffWithWorkingInDiffRight = 'mintlens.diffWithWorkingInDiffRight',
	DiffLineWithWorking = 'mintlens.diffLineWithWorking',
	DisconnectRemoteProvider = 'mintlens.disconnectRemoteProvider',
	DisableDebugLogging = 'mintlens.disableDebugLogging',
	EnableDebugLogging = 'mintlens.enableDebugLogging',
	ExternalDiff = 'mintlens.externalDiff',
	ExternalDiffAll = 'mintlens.externalDiffAll',
	FetchRepositories = 'mintlens.fetchRepositories',
	InviteToLiveShare = 'mintlens.inviteToLiveShare',
	OpenBlamePriorToChange = 'mintlens.openBlamePriorToChange',
	OpenBranchesOnRemote = 'mintlens.openBranchesOnRemote',
	OpenBranchOnRemote = 'mintlens.openBranchOnRemote',
	OpenChangedFiles = 'mintlens.openChangedFiles',
	OpenCommitOnRemote = 'mintlens.openCommitOnRemote',
	OpenComparisonOnRemote = 'mintlens.openComparisonOnRemote',
	OpenFileHistory = 'mintlens.openFileHistory',
	OpenFileFromRemote = 'mintlens.openFileFromRemote',
	OpenFileOnRemote = 'mintlens.openFileOnRemote',
	OpenFileOnRemoteFrom = 'mintlens.openFileOnRemoteFrom',
	OpenFileAtRevision = 'mintlens.openFileRevision',
	OpenFileAtRevisionFrom = 'mintlens.openFileRevisionFrom',
	OpenFolderHistory = 'mintlens.openFolderHistory',
	OpenOnRemote = 'mintlens.openOnRemote',
	OpenIssueOnRemote = 'mintlens.openIssueOnRemote',
	OpenPullRequestOnRemote = 'mintlens.openPullRequestOnRemote',
	OpenAssociatedPullRequestOnRemote = 'mintlens.openAssociatedPullRequestOnRemote',
	OpenRepoOnRemote = 'mintlens.openRepoOnRemote',
	OpenRevisionFile = 'mintlens.openRevisionFile',
	OpenRevisionFileInDiffLeft = 'mintlens.openRevisionFileInDiffLeft',
	OpenRevisionFileInDiffRight = 'mintlens.openRevisionFileInDiffRight',
	OpenWorkingFile = 'mintlens.openWorkingFile',
	OpenWorkingFileInDiffLeft = 'mintlens.openWorkingFileInDiffLeft',
	OpenWorkingFileInDiffRight = 'mintlens.openWorkingFileInDiffRight',
	PullRepositories = 'mintlens.pullRepositories',
	PushRepositories = 'mintlens.pushRepositories',
	GitCommands = 'mintlens.gitCommands',
	GitCommandsBranch = 'mintlens.gitCommands.branch',
	GitCommandsCherryPick = 'mintlens.gitCommands.cherryPick',
	GitCommandsMerge = 'mintlens.gitCommands.merge',
	GitCommandsRebase = 'mintlens.gitCommands.rebase',
	GitCommandsReset = 'mintlens.gitCommands.reset',
	GitCommandsRevert = 'mintlens.gitCommands.revert',
	GitCommandsSwitch = 'mintlens.gitCommands.switch',
	GitCommandsTag = 'mintlens.gitCommands.tag',
	GitCommandsWorktree = 'mintlens.gitCommands.worktree',
	PlusHide = 'mintlens.plus.hide',
	PlusLearn = 'mintlens.plus.learn',
	PlusLoginOrSignUp = 'mintlens.plus.loginOrSignUp',
	PlusLogout = 'mintlens.plus.logout',
	PlusManage = 'mintlens.plus.manage',
	PlusPurchase = 'mintlens.plus.purchase',
	PlusResendVerification = 'mintlens.plus.resendVerification',
	PlusRestore = 'mintlens.plus.restore',
	PlusShowPlans = 'mintlens.plus.showPlans',
	PlusStartPreviewTrial = 'mintlens.plus.startPreviewTrial',
	PlusValidate = 'mintlens.plus.validate',
	QuickOpenFileHistory = 'mintlens.quickOpenFileHistory',
	RefreshHover = 'mintlens.refreshHover',
	ResetAvatarCache = 'mintlens.resetAvatarCache',
	ResetSuppressedWarnings = 'mintlens.resetSuppressedWarnings',
	RevealCommitInView = 'mintlens.revealCommitInView',
	SearchCommits = 'mintlens.showCommitSearch',
	SearchCommitsInView = 'mintlens.views.searchAndCompare.searchCommits',
	SetViewsLayout = 'mintlens.setViewsLayout',
	ShowCommitInView = 'mintlens.showCommitInView',
	ShowCommitsInView = 'mintlens.showCommitsInView',
	ShowLastQuickPick = 'mintlens.showLastQuickPick',
	ShowQuickBranchHistory = 'mintlens.showQuickBranchHistory',
	ShowQuickCommit = 'mintlens.showQuickCommitDetails',
	ShowQuickCommitFile = 'mintlens.showQuickCommitFileDetails',
	ShowQuickCurrentBranchHistory = 'mintlens.showQuickRepoHistory',
	ShowQuickFileHistory = 'mintlens.showQuickFileHistory',
	ShowQuickRepoStatus = 'mintlens.showQuickRepoStatus',
	ShowQuickCommitRevision = 'mintlens.showQuickRevisionDetails',
	ShowQuickCommitRevisionInDiffLeft = 'mintlens.showQuickRevisionDetailsInDiffLeft',
	ShowQuickCommitRevisionInDiffRight = 'mintlens.showQuickRevisionDetailsInDiffRight',
	ShowQuickStashList = 'mintlens.showQuickStashList',
	ShowSettingsPage = 'mintlens.showSettingsPage',
	ShowSettingsPageAndJumpToBranchesView = 'mintlens.showSettingsPage#branches-view',
	ShowSettingsPageAndJumpToCommitsView = 'mintlens.showSettingsPage#commits-view',
	ShowSettingsPageAndJumpToContributorsView = 'mintlens.showSettingsPage#contributors-view',
	ShowSettingsPageAndJumpToFileHistoryView = 'mintlens.showSettingsPage#file-history-view',
	ShowSettingsPageAndJumpToLineHistoryView = 'mintlens.showSettingsPage#line-history-view',
	ShowSettingsPageAndJumpToRemotesView = 'mintlens.showSettingsPage#remotes-view',
	ShowSettingsPageAndJumpToRepositoriesView = 'mintlens.showSettingsPage#repositories-view',
	ShowSettingsPageAndJumpToSearchAndCompareView = 'mintlens.showSettingsPage#search-compare-view',
	ShowSettingsPageAndJumpToStashesView = 'mintlens.showSettingsPage#stashes-view',
	ShowSettingsPageAndJumpToTagsView = 'mintlens.showSettingsPage#tags-view',
	ShowSettingsPageAndJumpToViews = 'mintlens.showSettingsPage#views',
	RefreshTimelinePage = 'mintlens.refreshTimelinePage',
	ShowWelcomePage = 'mintlens.showWelcomePage',
	StashApply = 'mintlens.stashApply',
	StashSave = 'mintlens.stashSave',
	StashSaveFiles = 'mintlens.stashSaveFiles',
	SwitchMode = 'mintlens.switchMode',
	ToggleCodeLens = 'mintlens.toggleCodeLens',
	ToggleFileBlame = 'mintlens.toggleFileBlame',
	ToggleFileBlameInDiffLeft = 'mintlens.toggleFileBlameInDiffLeft',
	ToggleFileBlameInDiffRight = 'mintlens.toggleFileBlameInDiffRight',
	ToggleFileChanges = 'mintlens.toggleFileChanges',
	ToggleFileChangesOnly = 'mintlens.toggleFileChangesOnly',
	ToggleFileHeatmap = 'mintlens.toggleFileHeatmap',
	ToggleFileHeatmapInDiffLeft = 'mintlens.toggleFileHeatmapInDiffLeft',
	ToggleFileHeatmapInDiffRight = 'mintlens.toggleFileHeatmapInDiffRight',
	ToggleReviewMode = 'mintlens.toggleReviewMode',
	ToggleZenMode = 'mintlens.toggleZenMode',
	ViewsCopy = 'mintlens.views.copy',
	ViewsOpenDirectoryDiff = 'mintlens.views.openDirectoryDiff',
	ViewsOpenDirectoryDiffWithWorking = 'mintlens.views.openDirectoryDiffWithWorking',

	Deprecated_DiffHeadWith = 'mintlens.diffHeadWith',
	Deprecated_DiffWorkingWith = 'mintlens.diffWorkingWith',
	Deprecated_OpenBranchesInRemote = 'mintlens.openBranchesInRemote',
	Deprecated_OpenBranchInRemote = 'mintlens.openBranchInRemote',
	Deprecated_OpenCommitInRemote = 'mintlens.openCommitInRemote',
	Deprecated_OpenFileInRemote = 'mintlens.openFileInRemote',
	Deprecated_OpenInRemote = 'mintlens.openInRemote',
	Deprecated_OpenRepoInRemote = 'mintlens.openRepoInRemote',
	Deprecated_ShowFileHistoryInView = 'mintlens.showFileHistoryInView',

	// mintlify
	RefreshLinks = 'mintlify.refreshLinks',
	LinkCode = 'mintlify.linkCode',
	LinkDir = 'mintlify.linkDir',
	PreviewDoc = 'mintlify.previewDoc',
	PrefillDoc = 'mintlify.prefillDoc',
	RefreshViews = 'mintlify.refreshViews',
	DeleteLink = 'mintlify.deleteLink',
	DeleteDoc = 'mintlify.deleteDoc',
	RenameDoc = 'mintlify.renameDoc',
	RemoveMember = 'mintlify.removeMember',
	InviteMember = 'mintlify.inviteMember',
	HighlightConnection = 'mintlify.highlightConnection',
}

export const enum ContextKeys {
	ActionPrefix = 'mintlens:action:',
	KeyPrefix = 'mintlens:key:',

	ActiveFileStatus = 'mintlens:activeFileStatus',
	AnnotationStatus = 'mintlens:annotationStatus',
	Debugging = 'mintlens:debugging',
	DisabledToggleCodeLens = 'mintlens:disabledToggleCodeLens',
	Disabled = 'mintlens:disabled',
	Enabled = 'mintlens:enabled',
	HasConnectedRemotes = 'mintlens:hasConnectedRemotes',
	HasRemotes = 'mintlens:hasRemotes',
	HasRichRemotes = 'mintlens:hasRichRemotes',
	HasVirtualFolders = 'mintlens:hasVirtualFolders',
	Readonly = 'mintlens:readonly',
	TimelinePageFocused = 'mintlens:timelinePage:focused',
	Untrusted = 'mintlens:untrusted',
	ViewsCanCompare = 'mintlens:views:canCompare',
	ViewsCanCompareFile = 'mintlens:views:canCompare:file',
	ViewsCommitsMyCommitsOnly = 'mintlens:views:commits:myCommitsOnly',
	ViewsFileHistoryCanPin = 'mintlens:views:fileHistory:canPin',
	ViewsFileHistoryCursorFollowing = 'mintlens:views:fileHistory:cursorFollowing',
	ViewsFileHistoryEditorFollowing = 'mintlens:views:fileHistory:editorFollowing',
	ViewsLineHistoryEditorFollowing = 'mintlens:views:lineHistory:editorFollowing',
	ViewsRepositoriesAutoRefresh = 'mintlens:views:repositories:autoRefresh',
	ViewsSearchAndCompareKeepResults = 'mintlens:views:searchAndCompare:keepResults',
	Vsls = 'mintlens:vsls',

	Plus = 'mintlens:plus',
	PlusAllowed = 'mintlens:plus:allowed',
	PlusRequired = 'mintlens:plus:required',
	PlusState = 'mintlens:plus:state',

	// mintlify
	Links = 'mintlify.links',
}

export const enum CoreCommands {
	CloseActiveEditor = 'workbench.action.closeActiveEditor',
	CloseAllEditors = 'workbench.action.closeAllEditors',
	CursorMove = 'cursorMove',
	Diff = 'vscode.diff',
	EditorScroll = 'editorScroll',
	EditorShowHover = 'editor.action.showHover',
	ExecuteDocumentSymbolProvider = 'vscode.executeDocumentSymbolProvider',
	ExecuteCodeLensProvider = 'vscode.executeCodeLensProvider',
	FocusFilesExplorer = 'workbench.files.action.focusFilesExplorer',
	InstallExtension = 'workbench.extensions.installExtension',
	MoveViews = 'vscode.moveViews',
	Open = 'vscode.open',
	OpenFolder = 'vscode.openFolder',
	OpenInTerminal = 'openInTerminal',
	OpenWalkthrough = 'workbench.action.openWalkthrough',
	OpenWith = 'vscode.openWith',
	NextEditor = 'workbench.action.nextEditor',
	PreviewHtml = 'vscode.previewHtml',
	RevealLine = 'revealLine',
	RevealInExplorer = 'revealInExplorer',
	RevealInFileExplorer = 'revealFileInOS',
	SetContext = 'setContext',
	ShowExplorer = 'workbench.view.explorer',
	ShowReferences = 'editor.action.showReferences',
	ShowSCM = 'workbench.view.scm',
}

export const enum CoreGitCommands {
	Publish = 'git.publish',
	Pull = 'git.pull',
	PullRebase = 'git.pullRebase',
	Push = 'git.push',
	PushForce = 'git.pushForce',
	UndoCommit = 'git.undoCommit',
}

export const enum CoreGitConfiguration {
	AutoRepositoryDetection = 'git.autoRepositoryDetection',
	FetchOnPull = 'git.fetchOnPull',
	UseForcePushWithLease = 'git.useForcePushWithLease',
}

export const enum GlyphChars {
	AngleBracketLeftHeavy = '\u2770',
	AngleBracketRightHeavy = '\u2771',
	ArrowBack = '\u21a9',
	ArrowDown = '\u2193',
	ArrowDownUp = '\u21F5',
	ArrowDropRight = '\u2937',
	ArrowHeadRight = '\u27A4',
	ArrowLeft = '\u2190',
	ArrowLeftDouble = '\u21d0',
	ArrowLeftRight = '\u2194',
	ArrowLeftRightDouble = '\u21d4',
	ArrowLeftRightDoubleStrike = '\u21ce',
	ArrowLeftRightLong = '\u27f7',
	ArrowRight = '\u2192',
	ArrowRightDouble = '\u21d2',
	ArrowRightHollow = '\u21e8',
	ArrowUp = '\u2191',
	ArrowUpDown = '\u21C5',
	ArrowUpRight = '\u2197',
	ArrowsHalfLeftRight = '\u21cb',
	ArrowsHalfRightLeft = '\u21cc',
	ArrowsLeftRight = '\u21c6',
	ArrowsRightLeft = '\u21c4',
	Asterisk = '\u2217',
	Check = '✔',
	Dash = '\u2014',
	Dot = '\u2022',
	Ellipsis = '\u2026',
	EnDash = '\u2013',
	Envelope = '\u2709',
	EqualsTriple = '\u2261',
	Flag = '\u2691',
	FlagHollow = '\u2690',
	MiddleEllipsis = '\u22EF',
	MuchLessThan = '\u226A',
	MuchGreaterThan = '\u226B',
	Pencil = '\u270E',
	Space = '\u00a0',
	SpaceThin = '\u2009',
	SpaceThinnest = '\u200A',
	SquareWithBottomShadow = '\u274F',
	SquareWithTopShadow = '\u2750',
	Warning = '\u26a0',
	ZeroWidthSpace = '\u200b',
}

export const enum Schemes {
	DebugConsole = 'debug',
	File = 'file',
	Git = 'git',
	GitHub = 'github',
	MintLens = 'mintlens',
	Output = 'output',
	PRs = 'pr',
	Vsls = 'vsls',
	VslsScc = 'vsls-scc',
	Virtual = 'vscode-vfs',
}
